### ISSUE TITLE
Terms & Condition

### ISSUE THREAD

**Issue by lytzV** [disk91/helium-chirpstack#64]
### When do users need to agree to the Terms & Condition?
Whenever there is no record of this user (email) agreeing to the latest T&C.
i.e. new user OR when T&C has been updated.

The version string of the T&C should probably be an environment variable.

### What should be stored?
Upon the user clicking "I've read and agree." The user will be let into Chirpstack UI, and the backend will log
- user email
- timestamp when user agreed to the t&c
- the version string of the latest T&C

These information needs to persist (i.e. no periodic purging)

**Comment by disk91** [comment]
Added to the solution.
