### ISSUE TITLE
Network Session Key doesn't get updated after MQTT reconnect

### ISSUE THREAD

**Issue by vkynchev** [disk91/helium-chirpstack#66]
I've stumbled across an issue with uplinks. A device is able to join at all times - DevEUI is added to OUI routing information. On a join event the NSK (Network Session Key) gets updated in OUI routing information and later uplinks and downlinks are all being sent out fine.

In a case where MQTT connection drops or the clients are kicked out of the server (either manually or for some mqtt server reason) the NSK never gets updated in OUI routing and following uplinks are never delivered to Chirpstack.

I'm attaching screenshots from the application logs (UTC timezone) + device serial logs showing the obtained keys (EEST timezone)

**Occurence 1:**

Application logs: <img width="1618" alt="Screenshot 2023-08-07 at 22 09 32" src="https://github.com/disk91/helium-chirpstack/assets/10143016/d46fdd96-9099-46d2-bd28-a3dd10869aa4">

Successful join (with updated NSK): <img width="788" alt="Screenshot 2023-08-07 at 22 09 51" src="https://github.com/disk91/helium-chirpstack/assets/10143016/3f82d074-de49-4b38-b825-e7239ee30a4c">

Successful join after MQTT reconnection: <img width="755" alt="Screenshot 2023-08-07 at 22 17 26" src="https://github.com/disk91/helium-chirpstack/assets/10143016/f75509e9-418a-4056-8e3c-d47fe3202174">

**Occurence 2:**

Application logs: <img width="1607" alt="Screenshot 2023-08-07 at 22 12 10" src="https://github.com/disk91/helium-chirpstack/assets/10143016/745446b5-7f99-4784-945a-6036adb908d4">

Successful join after MQTT reconnection: <img width="812" alt="Screenshot 2023-08-07 at 22 12 15" src="https://github.com/disk91/helium-chirpstack/assets/10143016/233c7a65-d639-4e93-93ca-07e57b4f0bcb">

**Comment by disk91** [comment]
Hello,
This is a known problem i’ll fix in tte coming days. Currently when mqtt restart, you must restart helium contained. 
Paul

**Comment by vkynchev** [comment]
@disk91 I already fixed it, it's in the same PR as the redis ssl fix. 🙂

**Comment by disk91** [comment]
Yes i’ve seen that. But i want to fix it differently. 
Better not to make fat pull request. Please split topic in different branches so it will be easier to me to merge that can be directly merge and reject what i’ll manage differently. 
btw. Thank you for contributing

**Comment by disk91** [comment]
integrated in 1.3.0
