### ISSUE TITLE
ADR Margin

### ISSUE THREAD

**Issue by Hobietime** [disk91/helium-chirpstack#69]
https://github.com/disk91/helium-chirpstack/blob/ee834f0772be053a6d17da3c141ed6fd55633dcf/chirpstack/configuration/chirpstack/region_us915_1.toml#L152

Hello,

I have been having issues with the ADR algorithm being too aggressive on console.helium-iot.xyz.

I can share with you the details of the problematic sensors privately.

I propose increasing the default margin from 10 to 15.

If you would like I can submit a pull request with this change to all regions.

Caio

**Comment by disk91** [comment]
done in 1.3.1 (you need to copy the region_files in /helium/... )
