### ISSUE TITLE
Disabling certain UIs

### ISSUE THREAD

**Issue by lytzV** [disk91/helium-chirpstack#70]
Add env var to so tenants can't see the option to nor perform the action to
• create other tenants
• purchase data credits
• Tenant setup & last 7 days stats
<img width="1238" alt="Screen Shot 2023-08-11 at 10 56 05 AM" src="https://github.com/disk91/helium-chirpstack/assets/44751312/0283eab9-74b3-4000-9b62-082b5219bef6">

**Comment by disk91** [comment]
Tenant setup is required for changing the max_copy and can't be made another way ; so this can't be removed without having a end-user impact
The other menu entries have been removed when the corresponding DIS_xxx Mkefile entries are set to true

**Comment by lytzV** [comment]
Sorry not the whole tenant set up see my screenshot, just the component in my screenshot. The max_copy is highly beneficial I agree, but we don't want tenants to see DC related information as our billing model doesn't work that way.

**Comment by disk91** [comment]
I will see that later, not a priority.
