### ISSUE TITLE
Whitespace in regional configuration files breaks kubernetes deployments

### ISSUE THREAD

**Issue by shawaj** [disk91/helium-chirpstack#88]
You have whitespace in line endings and empty lines in your configuration files.

This breaks things in kubernetes and various other environments.

It's clear from #87 and discord conversations that you have very little interest in solving this. But adding an issue in case you change your mind.

**Comment by disk91** [comment]
Whitespace removed from toml files.

**Comment by shawaj** [comment]
Closed by 4085d9f and upstream at https://github.com/chirpstack/chirpstack/pull/308
